### ISSUE TITLE
[Shapes] Update shapes on Work page

### ISSUE THREAD

**Issue by locks** [mainmatter/mainmatter.com#1003]
With the introduction of the new Services sub-pages, a new shape design language was introduced and other pages on the website need to be updated accordingly.
Part of https://github.com/simplabs/simplabs.github.io/issues/906.

## Tasks
- [x] Replace Trainline case study shape
- [x] Replace Timify case study shape
- [x] Update layout for "More Case Studies"
- [x] Replace Playbook shape

## References
- Abstract: https://share.goabstract.com/45b44110-0d2f-47c0-b367-84a1dbeefd22?collectionLayerId=61d00441-679d-4e3b-a325-5b7eb40699e0&mode=design

**Comment by locks** [comment]
This seems to be done.
