### ISSUE TITLE
[Shapes] Update shapes on Ember Expertise page

### ISSUE THREAD

**Issue by locks** [mainmatter/mainmatter.com#1017]
With the introduction of the new Services sub-pages, a new shape design language was introduced and other pages on the website need to be updated accordingly.
Part of https://github.com/simplabs/simplabs.github.io/issues/906.

## Tasks
- [x] Update header
- [x] Use new shape for "Official Ember.js Sponsor" and move it to before "We love open source"
- [x] Change open source projects layout to two columns
- [x] Replace Documentary shape

## References
- Abstract: https://share.goabstract.com/45b44110-0d2f-47c0-b367-84a1dbeefd22?collectionLayerId=686c8de8-99d7-4af6-b5ab-f23921e45055&mode=design
