### ISSUE TITLE
Make Cookie Banner compliant

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1166]
We are currently simple display the cookie banner but track users with GA anyway. I don't think that's compliant with the law really and we'd have to delay any tracking until the user actively consents.

### Tasks

- [ ] extract JS code in `lib/google-analytics/index.js` into a (global) function that's not invoked immediately
- [ ] invoke global function when users consents to cookie usage (see https://github.com/simplabs/simplabs.github.io/blob/master/src/ui/components/CookieBanner/template.hbs#L8) – it would make sense to rename that to `@onConsent` or so
- [ ] if the cookie banner is invisible anyway (`isCookieBannerVisible === false`), invoke the global function lazily (using `requestIdleCallback`) from the `Simplabs` component's constructor

**Comment by marcoow** [comment]
This doesn't really make sense. If we do this (which I think we have to), the data we get from GA will be completely irrelevant as it only represents a (small) fraction of our actual traffic. Instead, we should probably remove GA altogether and use Netlify Analytics instead which works without JS, cookies etc.
