### ISSUE TITLE
Fix unnecessary redirects

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1308]
Netlify directs internal URLs not ending with a `/` to their equivalent with a trailing `/`, e.g. `https://simplabs.com/blog/author/pichfl` redirects to `https://simplabs.com/blog/author/pichfl/`. We do have some internal links that do not apply the trailing slash and thus result in unnecessary redirects. Once the app has rehydrated in the browser and is running client-side that is not a problem since the request never reaches netlify anyway but we should still clean that up.

### TODO

- [x] add trailing slashes
  - [x] when linking to an author's posts ([here](https://github.com/simplabs/simplabs.github.io/blob/master/lib/generate-blog/lib/templates/author/template.hbs#L22), [here](https://github.com/simplabs/simplabs.github.io/blob/master/lib/generate-blog/lib/templates/post/template.hbs#L72) and [here](https://github.com/simplabs/simplabs.github.io/blob/master/lib/generate-blog/lib/templates/author/template.hbs#L50))
  - [x] when building the link to a post ([here](https://github.com/simplabs/simplabs.github.io/blob/master/lib/generate-blog/lib/components-builder.js#L150))
  - [x] when building a post's url in the feed builder ([here](https://github.com/simplabs/simplabs.github.io/blob/master/lib/generate-blog/lib/feed-builder.js#L50))
  - [x] when linking to the product development page ([here](https://github.com/simplabs/simplabs.github.io/blob/master/src/ui/components/PageDigitalProducts/template.hbs#L149))
  - [x] when linking to the product design page ([here](https://github.com/simplabs/simplabs.github.io/blob/master/src/ui/components/PageDigitalProducts/template.hbs#L99))
