### ISSUE TITLE
Add error tracking

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1902]
We should have at least some error tracking in place. Of course this is a static page which little potential for things to go wrong and 99% of the JS is optional anyway really but it would be good to have a feeling for whether things generally work or not. One specific case where we'd absolutely need to know if errors happen is the contact form – if that doesn't submit successfully, we should be aware.

## TODOs

- [x] add general Sentry catchall code for JS
- [x] report submission errors of the contact form to Sentry explicitly (including the original message so that isn't lost)
- [x] add a clause about usage of Sentry to the [privacy policy](https://mainmatter.com/privacy/)
- [x] enable source maps for JS (as we'll need them for Sentry)
