### ISSUE TITLE
Add new case studies

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1914]
We have case studies for 3 projects that we haven't put on the website yet: Experteer, MVB, and AIS. Those need to be added to the site.

## TODOs

- [x] add case study page for Experteer
- [x] add case study page for MVB
- [x] add case study page for AIS
- [x] update featured case studies on `/work` page so that the order of the featured case studies is Qonto, MVB, Trainline, Experteer, AIS, Timify, dd-wrt, Expedition – the rows of small project teasers in between remain the same
- [x] replace the small features of the Timify and dd-wrt and case studies on the landing page with Experteer and MVB so that the order of the small ones below the large Qonto one is Experteer, Trainline, MVB
- [x] add the new case studies to the list under _"Work"_ in the footer (order being the same as on the `/work` page)

## Resources

* [Designs](https://www.sketch.com/s/7baa7317-7ec9-48b5-9584-4edb6163c143/p/09ABE235-F655-4723-9ADF-FCD5D2CF0F9F/canvas)
* Case study text, original quotes and screenshots:
  * [AIS](https://www.notion.so/mainmatter/AIS-505b59ed44404128bf87ffafe189590b)
  * [MVB](https://www.notion.so/mainmatter/MVB-b9b2a96236a24a6eaf2b4c4dbfc2a64b)
  * [Experteer](https://www.notion.so/mainmatter/Experteer-CV-to-Profile-8d32a27c5c844280a9a4af8434d1ebab)

## To Prepare

- [x] The AIS case study design is missing the quote

**Comment by marcoow** [comment]
done
