### ISSUE TITLE
Replace Mar on workshop pages

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1928]
Mar has left quite some time ago but is still featured on our workshop pages. We should replace her:

* The [digtital product strategy workshop](https://mainmatter.com/services/workshops/digital-product-strategy/) will be done by Marco and Florian now.
* The [interface inventory workshop](https://mainmatter.com/services/workshops/design-system-kickoff-interface-inventory/) **could maybe** be done by Florian; if he doesn't feel comfortable doing one, we'll just remove it for now.

## TODO

- [x] replace Mar's data with Florian's for the [digtital product strategy workshop](https://mainmatter.com/services/workshops/digital-product-strategy/)
- [x] replace Mar's data with Florian's for the [interface inventory workshop](https://mainmatter.com/services/workshops/design-system-kickoff-interface-inventory/)

## TBD

- [x] we need a bio text for Florian for the [digtital product strategy workshop](https://mainmatter.com/services/workshops/digital-product-strategy/)
- [x] does Florian want to take over the interface inventory workshop?

**Comment by pichfl** [comment]
Potential bio:

> Florian bridges the gap between development and design in his clients’ projects for more than 7 years. He created user experiences and design systems for established brands like Audi, BASF, BMW, and Zurich Insurance.

**Comment by marcoow** [comment]
done
