### ISSUE TITLE
Replace Ricardo with Gabor on Ember workshop page

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1930]
As Ricardo will be leaving us and Gabor has taken over responsibility for the Ember workshop, we should put him on the [Ember workshop page](https://mainmatter.com/services/workshops/hands-on-ember/) with Marco.

## TODO

- [ ] replace Ricardo's data with Gabor's

## TBD

- [ ] what title to use for Gabor?
- [x] what image to use?
- [x] what bio text to use?

**Comment by zeppelin** [comment]
> Gabor is a very early Ember user since its pre-1.0 years, successfully completing several projects and helping teams with their applications, teaching them best practices relevant to either the latest or classic versions of Ember.
