### ISSUE TITLE
Add Rust Consulting landing page

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1944]
To be able to better promote our Rust services, we want to set up a dedicated landing page for it, similar to what we have already for Ember.js and Elixir.

## TODO

- [x] define a new collection `rustPosts` in [`.eleventy.js`](https://github.com/mainmatter/mainmatter.com/blob/master/.eleventy.js) that filters posts by the `rust` tag (the same way that [`elixirPosts`](https://github.com/mainmatter/mainmatter.com/blob/master/.eleventy.js#L50) works essentially)
- [x] implement page according to designs
  * all elements can be reused from the existing Ember.js and Elixir landing pages
- [x] add link _"Rust"_ to this page at the bottom of the _"Resources"_ list in the footer

## Resources

* [Designs](https://www.sketch.com/s/7baa7317-7ec9-48b5-9584-4edb6163c143/a/l1MLK3e)
* Page metadata:
  * path: `/rust-consulting/`
  * title: `"Enable your team to leverage Rust"`
  * description: `"Mainmatter enables teams to adopt Rust in their web projects and increase performance, efficiency, and maintainability."`
