### ISSUE TITLE
Replace old MVB logo with new one

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1948]
MVB replaced their logo some time ago and we're still using the old one. They are almost the same but the **old one is lowercase**, the **new one is uppercase**.

## TODO

- [x] replace logo in mini project description on [work page](https://mainmatter.com/work/) (see below)
- [x] replace logo in [case study](https://mainmatter.com/cases/mvb/) (see below)
- [x] fix spelling everywhere on the website (_"MVB"_ instead of _"mvb"_)

## Resources:

* logos: https://www.notion.so/mainmatter/MVB-b9b2a96236a24a6eaf2b4c4dbfc2a64b
* MVB logo on work page: <img width="467" alt="Bildschirm­foto 2022-11-16 um 08 31 05" src="https://user-images.githubusercontent.com/1510/202115534-d771f586-425d-4971-a82d-1d76455f1b4d.png">
* MVB logo in case study: <img width="868" alt="Bildschirm­foto 2022-11-16 um 08 32 56" src="https://user-images.githubusercontent.com/1510/202115781-187917ef-efe4-4744-920d-4101bc561d70.png">

**Comment by marcoow** [comment]
@emmasofiah2o this would be a good first issue for you to try – should be relatively straight forward
