### ISSUE TITLE
Add conversion tracking

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1949]
On simplabs.com, we had conversion tracking for when the contact form was submitted. When releasing the rebranding, we dropped that and should restore it so we have an idea of how well certain traffic sources perform.

## TODO

- [x] set up a new custom event goal in Plausible (see below)
- [x] ensure we load the Plausible script needed for conversion tracking (see below)
- [x] restore the old tracking code for when the contact form is submitted (see below; add [here](https://github.com/mainmatter/mainmatter.com/blob/master/src/assets/js/contact-form.js#L18))

## Resources

* Plausible docs on setting up custom event goals: https://plausible.io/docs/custom-event-goals#2-create-a-custom-event-goal-in-your-plausible-analytics-account
* Plausible docs on loading conversion tracking scripts: https://plausible.io/docs/custom-event-goals#1-trigger-custom-events-with-javascript-on-your-site
* Old code from simplabs.com for tracking the event: https://github.com/mainmatter/mainmatter.com/blob/0edf32fe5d1e32da68b4125d5e0bd3dd5db637f1/src/ui/components/FormContact/component.ts#L54-L57 (we're checking whether `plausible` is present to keep things simple; also the Plausible docs say only to submit the form when the tracking worked but since the submission is more important we don't want to make it dependent on the tracking and simplabs track independently)
