### ISSUE TITLE
Generate blog post components on the fly

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#272]
For blog posts, we'd like to maintain the same mechanism we're using now for the new simplabs.com as well. That means posts are written as markdown files with some front matter that describes the category, author etc. In the end, those posts would end up as glimmer components that are routed to individual routes. These components would have to be generated (not generated as actual files in `src/ui` but generated and added to the app tree) as part of the build.

### TODO

- [x] define what a blog post component looks like (this is before we have the auto-generation so that we know what we'll be auto-generating eventually)
- [x] auto-generate blog post components on the fly during the build and add them to the app tree
- [x] [add routes](https://github.com/simplabs/simplabs.github.io/blob/new-simplabs/config/routes-map.js) for the auto-generated blog posts during build time
- [x] add a blog index page that lists all blog posts (or the last 3 or whatever); or maybe this is a curated page?
- [ ] add a [service](https://gist.github.com/mixonic/acbc9b8d57819e2f2c77b206ab7f422e) that knows which blog post components are for which tags, by which author etc. so that we can implement something like _"here are the 3 latest ember posts"_

**Comment by marcoow** [comment]
closed via #324
