### ISSUE TITLE
Add service worker

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#274]
We should have a service worker that caches all static assets and serves the app from cache when offline. This is very similar to what we're using for [Breethe](https://github.com/simplabs/breethe-client/blob/master/lib/service-worker/workers/service-worker.js).

### TODO

- [x] add service worker (probably via an in-repo-addon as we're doing for Breethe)
- [x] make sure service worker itself is not fingerprinted (and not cached)
- [x] cache all static assets in service worker cache, serve from it
- [x] serve the app's html from service worker cache when the browser is offline

**Comment by marcoow** [comment]
done via #524
