### ISSUE TITLE
Use proper SSR with rehydration

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#278]
Currently, we're using the basic Glimmer rendered and do SSR with just Puppeteer and not real SSR where the browser already gets a pre-rendered response for the first request (which also means that we have to clear out the complete DOM tree and replace it once the app boots in the browsers). What we should do instead is use real Glimmer SSR with a server that does the pre-rendering and then start the app with the rehydrating rendered that just connects to the existing DOM instead of replacing it all. We could still use Puppeteer to snapshot the initial response, inline critical CSS (and potentially apply additional optimizations in the future) etc.

### TODO

- [x] build an SSR version of the app in addition to the client-rendered one (see Breethe for reference: https://github.com/simplabs/breethe-client/tree/master/ssr)
- [x] in the prerender script, start that app in a Node.js server instead of serving the static app (see Breethe for reference: https://github.com/simplabs/breethe-client/blob/master/ssr-server.js)
- [x] make sure the SSR DOM tree doesn't get modified when the app rehydrates in Puppeteer or if it does, change the prerender script so that it does not actually start the app up so the SSR-rendered tree remains in place
- [x] replace the rendered on the client side with the rehydrating renderer that connects to the SSR tree instead of replacing it (see here: https://github.com/glimmerjs/glimmer.js/blob/master/packages/@glimmer/application/src/builders/rehydrating-builder.ts)

**Comment by marcoow** [comment]
closed via #288
