### ISSUE TITLE
Add News section

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#311]
All the updates that @mrmrcoleman publishes currently end up in the blog (as that's the only way for now to publish anything on the website). Given the blog is really targeted at engineers though, having these business updates in it does not really make sense from a content perspective and might even be off-putting to some of the audience. We should create a news section that we separate from the blog (while using a similar mechanism that allows us to create new posts by just adding a Mardown file; although we'd probably not need author, category etc. for those) and show that on a separate page on the website, maybe teasering it from the homepage.

### TODO

- [ ] define data elements for news (title, body, author? etc.)
- [ ] create visual design (single post, list page, teaser)
- [ ] decide where the page integrates in the website, where it is teasered etc.
- [ ] generate blob content during build time based on markdown, see #272
- [ ] split news into their own bundle, see #273 
- [ ] add pagination to the new pages, see #440

**Comment by marcoow** [comment]
We should check whether people that read our news on the blog (if there is a substantial number of readers at all), also go on to read other (technical) blog posts or other parts of the page.
