### ISSUE TITLE
404 error page

### ISSUE THREAD

**Issue by pichfl** [mainmatter/mainmatter.com#356]
We should have an error page so we can track possible link errors or stuff people may be looking for.

### TODO

- [x] add 404 page component
- [x] design 404 page component
- [x] handle transitions to unknown path on client side
- [x] respond with 404 page from server for unknown paths (@marcoow: we currently pre-render the 404 page as `/404/index.html` - setting that as the default response for 404 errors should only be a server side setting)

**Comment by marcoow** [comment]
done via #375
