### ISSUE TITLE
Responsive layouts

### ISSUE THREAD

**Issue by pichfl** [mainmatter/mainmatter.com#357]
While I'm still not quite happy with the state of layout abstractions, I think it's time to ensure the site works well on mobile devices.

Once we know what the relevant breakpoints are we need to update the pre-renderer so it injects the critical CSS for the respective breakpoints - see #457.

### TODO

- [ ] the shapes are displaced on some mobiles (seems to be the case on iOS but also when simulating a Galaxy S5 in Chrome): 

<img width="513" alt="Bildschirmfoto 2019-05-25 um 13 02 24" src="https://user-images.githubusercontent.com/1510/58368437-66e2cf80-7eed-11e9-9c38-62034d61932e.png">

- [ ] the author badge on mobile is currently hidden and needs to be shown again and fixed so it renders correctly/reasonably on mobile
- [ ] intermediate resolutions between desktop and mobile (e.g. iPad) are currently broken and need to be addressed as well, e.g.:

![Bildschirmfoto 2019-05-25 um 13 08 04](https://user-images.githubusercontent.com/1510/58368502-423b2780-7eee-11e9-8056-7060a7c880c6.png)

- [ ] some of the shapes have excessive amounts of whitespace in some resolutions:

<img width="830" alt="Bildschirmfoto 2019-05-27 um 14 40 33" src="https://user-images.githubusercontent.com/1510/58420424-8284dc00-808d-11e9-9706-223d0ec0998c.png">

- [ ] we should restore the parallax scrolling effects for the shapes on the desktop

**Comment by marcoow** [comment]
@ghislaineguerin for context: we have 90% desktop users so while we want a mobile version that works, it's not worth (for now) to spend a lot of work to make the mobile version super awesome.

**Comment by ghislaineguerin** [comment]
Homepage Responsive Layout:
https://share.goabstract.com/e0d0094d-e983-4c8e-a59d-d7d4c36cdb57?mode=design&sha=90cf65596cb8369829a4e33f3bc6ecc12d12dca6

I will add more pages as I complete them.

**Comment by marcoow** [comment]
I added a list of TODOs at the top and am moving this as the top prio to the post-launch fixes.

**Comment by marcoow** [comment]
setting this as blocked as it depends on #569, #570, #571, #573
