### ISSUE TITLE
Add talks page

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#377]
The talks page is supposed to list all talks that we gave at conferences or meetups in the past with embedded videos and/or links to the slidedecks.

The design is available [here](https://projects.invisionapp.com/d/main#/console/16581855/343841153/preview).

### TODO

- [x] add static page with all possible content (this should include pagination)
- [x] generate that page from markdown files (like for the blog and calendar)
- [x] split page into a separate bundle

**Comment by marcoow** [comment]
done via #434
