### ISSUE TITLE
Cross-reference services

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#389]
We should cross-reference the service pages so that visitors can easily switch between the services without having to go through the footer or the `/services` index page.

### TODO

- [x] replace Timify success story with trainline (we did team augmentation for trainline, not for timify)
- [ ] come up with a design to cross-reference the other services on the page (featuring in the sidebar doesn't work as that is already full - maybe we can feature at the bottom instead, similar to what we'll be doing in #552)
- [ ] implement the above design

**Comment by marcoow** [comment]
we'll add the cross references to the other services later
