### ISSUE TITLE
Contact Forms

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#400]
We have contact forms on several pages which need to be built.

### TODO

- [x] design forms incl. 3 states (submitting, error, success)
- [x] add text section for some explanatory text (as described in #408)
- [x] build HTML/CSS for these states
- [x] make the forms functional and add tests

**Comment by marcoow** [comment]
@ghislaineguerin can you add the design for the 3 stages?

**Comment by ghislaineguerin** [comment]
@marcoow sure, I will work on this next.
