### ISSUE TITLE
Investigate ways to improve visual interest of blog posts

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#438]
We currently show a title/preview image for blog posts when they are referred to from another post, e.g.:

<img width="1436" alt="Bildschirmfoto 2019-05-16 um 12 13 43" src="https://user-images.githubusercontent.com/1510/57846248-14f6c700-77d4-11e9-9dcd-468c192f1607.png">

That image can be configured per post in the `.md` file, e.g.: https://github.com/simplabs/simplabs.github.io/blob/new-simplabs/_posts/2019-03-18-emberconf-update.md (see `teaser-background` and `teaser-image` in the post metadata).

I think it'd be good to use that image on the post itself maybe which would also make the post's own page visually more interesting. We should also prepare and configure these images for more of the existing posts (at least the popular ones) to make them more appealing.

### TODO

- [ ] figure out how we can use these post-specific images on the posts itself (maybe a shape at the head of the post or so)
- [ ] implement that
- [ ] use the image for the structured data added in #656 as well (which currently uses our logo)
- [ ] prepare and configure images for most popular existing posts (we can just have a look at GA for identifying those)

**Comment by pichfl** [comment]
Closed in favor of #561
