### ISSUE TITLE
Consider adding more visual content above the fold

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#439]
We currently have almost only text above the fold which makes the page very clean but also potentially a little boring. We should consider adding more visual content above the fold to make the page more engaging (result of the consideration might be a decision not to do it of course).

This issue is not for the actual implementation but only for doing research and experimentation and (potentially) preparing a follow-up issue and TODOs for the implementation.

### TODO

- [ ] consider adding more content above the fold and evaluate potential designs
- [ ] prepare designs per page
- [ ] prepare a follow-up issue for the actual implementation with well-described TODOs etc.
