### ISSUE TITLE
Add cookie banner

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#536]
We are required to show a banner that makes users aware that our page uses cookies and that links to the privacy policy with all of the legal information.

### TODO

- [x] build cookie banner component that is shown if the user has not accepted cookies on our page previously
- [x] add functionality for hiding the banner that persists that choice in a cookie and prevents the banner from showing upon the next visit
- [x] revisit the design of the banner and make sure it's in line with the rest of our design - after all the cookie banner is something that 90% of our users will see

**Comment by marcoow** [comment]
#537 adds a banner which is good enough for now but someone with more design expertise than myself should look at this again and make it nicer.
