### ISSUE TITLE
SEO improvements

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#539]
We are currently doing a relatively poor job with SEO with us not showing up for a search for e.g. _"ember consulting"_ **at all**. There is obviously much to improve there and we need to spend some time on that, figuring out what we can do to improve the situation. We should not just start making random adjustments but come up with a plan first. I guess it probably makes sense to use tools like Google Search Console (https://search.google.com/search-console/about) to find out what to improve but I'm sure some people on our team have experience with this already.

As a result of this issue, we should have another issue with a list of TODOs, sorted by their effort/impact ratio so that we complete the low-hanging-fruit issues first before going to the more complex ones.

### TODO

- [x] compile a list of things we need to improve
- [x] order that list by their effort/impact ratio so we do the easy ones with most impact first
- [x] create a new issue with the above list and potentially some guidance how to complete each TODO

**Comment by pichfl** [comment]
My list so far:

- [x] `<meta name="description" content="...add something sensible here...">` 160 characters or less per page. Not used for SEO directly, but improves the text below the title in search results and is used as fallback for Open Graph content (Facebook, Twitter, Slack, etc)
- [x] Create `og:image` meta for blog posts and at least all site sections, especially those that will get linked. - shows on all social platforms and things like Slack
- [x] ~Ensure a proper document outline exists (we got better with that already, check for headlines and such)~
- [x] Verify image descriptions: Check if necessary or missing. Many images on our site are purely decoration and do not actually convey content meaning. Use empty alt attributes for those. Missing alt attributes are equally bad, as this will force screen readers to read the src, so an empty string is recommended for decoration. - Needs discussion what actually counts as content. 
- [x] Give @pichfl access to Analytics

To be continued.

**Comment by ghislaineguerin** [comment]
## SERP Improvements
- [x] Pages are missing H1-1 and H1-2 tags (this includes blog). We should assign an h1 tag to the header logo and title of every page.
- [x] Redirect /clients to /work
- [x] Work page SERP needs to be updated to include a general description of our work and not just Trainline case study
- [x] Meta description is missing for all pages. Decide if we want to add this for some pages to improve CTR, otherwise leave page without (for example pages like the blog with a low CTR could use a better description)
- [x] Meta keywords are the same for all pages. Review duplicated and remove or update in cases where it doesn't match the content or copy.

## Content Quality
- [ ] Develop plan to lower the bounce rate (>80%) for pages with the highest impressions / CTR (From Search Console)
- [ ] Develop plan to increase CTR on keywords for which we have high impressions / high business value (spa app, qunit dom, elixir application, ember training)
- [ ] Develop plan to increase traffic in Europe (most organic traffic is US)
- [ ] Disavow low quality backlinks to our site (most fall into this category) and develop plan to increase high quality backlinks
- [ ] Develop plan to increase positioning of our pages on the 4-10 position

## Image Results
- [x] Add featured images to blog posts and create thumbnails of our talks with the highest impressions on image search (ember, pwa, glimmer)

## Blog
- [x] Investigate the possibility of creating rich cards for "how to" blog posts with high impressions
- [x] Apply structured data markup to all blog articles. See example below
![image](https://user-images.githubusercontent.com/845767/61204098-af985700-a6ec-11e9-9f99-0334b1ab69f7.png)

**Comment by ghislaineguerin** [comment]
@marcoow @pichfl this is just part 1 of many improvements I have identified. Please take a look and let me know if some items don't make sense or could use more details. I do have data sources for each item, but I rather post those somewhere else.

**Comment by marcoow** [comment]
So I'd say the following are easy to do and should have good impact already?

* Add meta description and keywords to all pages; this needs to integrate with the routing somehow (we'll probably want to specify that content in the routes config or the main page component for the respective page somehow) and also requires some new properties for the blog posts so that we can specify the keywords and meta description in the front matter of each post?
* review document structure and make sure we properly use h1/h2 etc.
* redirect /clients to /work
* apply structured data markup to all blog articles; we should be able to auto-generate that from each post's front matter I guess

@pichfl, @ghislaineguerin: does that make sense?

**Comment by ghislaineguerin** [comment]
@marcoow agreed, I think those are good tasks to begin with.

**Comment by marcoow** [comment]
@ghislaineguerin are you leading the next iteration and will create issues for these?

**Comment by ghislaineguerin** [comment]
@marcoow yes, will do.
