### ISSUE TITLE
Improve layout for blog posts

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#561]
The current layout for blog posts still lacks refinement. 

### TODO

- [x] Responsiveness isn't used everywhere
- [x] Autor card is missing on mobile
- [x] New design
- [x] Update layout code
- [x] Improve table typography
- [x] Images
- [x] embedded contents are not handled properly
- [x] ~Title images should be used more prominently~ → see #438

### Steps

- Create new layout for both the narrow and wide screen layout with samples for possible content types
- Implement that
- Prepare and configure images for most popular existing posts (we can just have a look at GA for identifying those)

**Comment by marcoow** [comment]
This might be obsolete once we have #573, #574

**Comment by marcoow** [comment]
I realized also that tables don't render nicely, see e.g. https://simplabs.com/blog/2017/12/04/enginification
