### ISSUE TITLE
Improve baseline CSS styles

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#569]
We currently only have very rudimentary baseline and reset styles so that we have to style everything with css blocks which can be tedious and also requires assigning classes to all elements, e.g. blog post that are generated from markdown. It also makes things in css-blocks more complex as we have to handle all of the baseline stuff there.

### TODO

- [x] move custom properties from css-blocks into the baseline so we don't have to extend `screen.block.css` everywhere
- [x] extract default styles for text, links etc. from the blocks and keep them in the baseline css
- [x] remove class assignments from the markdown handling code where the respective styles have been replaced with classes in the baseline
