### ISSUE TITLE
Separate CSS Block for spacing

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#570]
We currently have various classes for defining spacing and offsets between elements that also require a number of extra wrappers that would not normally be necessary. That makes everything pretty complex and also makes building the responsive version of the page correctly. Instead, we'll reduce these classes to one spacing block with a number of helper classes that can be used throughout the project.

### TODO

- [x] identify and define spacing classes in the new spacing block
- [x] apply the new classes to the existing page
- [x] remove the spacing classes in `main-block.block.scss`
