### ISSUE TITLE
Separate CSS Block for page layout

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#571]
We currently have various classes for defining the page's layout structure that also require a number of extra wrappers that would not normally be necessary. That makes everything pretty complex and also makes building the responsive version of the page correctly. Instead, we'll reduce these classes to one layout block with a number of helper classes that can be used throughout the project.

### TODO

- [x] identify and define layut classes in the new layout block
- [x] apply the new classes to the existing page (which will allow us to remove various wrapper elements as well then)
- [x] remove the layout classes in `main-block.block.scss` and potentially the block altogether
