### ISSUE TITLE
Navigation active states

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#572]
We do not currently have an active state for the navigation so while we have a hover state, users don't know which page they're currently at.

### TODO

- [x] design an active state for the top navigation items
- [x] define a property for setting the active item on the `<Header>` component
- [x] set that new property in every page component where the `<Header>` component is invoked (also in generated page components like the blog)
- [x] add active state to mobile menu (white underline)

**Comment by ghislaineguerin** [comment]
@pichfl I will work on adding the design to sketch and you can take this after to implement.

**Comment by ghislaineguerin** [comment]
As part of this issue I also want to highlight the active navigation on mobile. Making the small label on top of the h1 a bit more prominent. 
@pichfl Does that make sense to you?
![IMG_0B0128049497-1](https://user-images.githubusercontent.com/845767/60675206-165f7a00-9e7c-11e9-8f72-70757cd5ec54.jpeg)

**Comment by pichfl** [comment]
I agree, we could make them a bit larger and more visible on mobile

**Comment by ghislaineguerin** [comment]
@pichfl 
I have finished adding to the abstract mockup what I think are simple navigation changes that can help with both:
- Navigation between pages
- Navigation within the page

## Desktop:
Desktop state is pretty simple, a bottom border should keep things minimal but bring enough attention to the active item.

![image](https://user-images.githubusercontent.com/845767/60868559-9e070900-a22d-11e9-886a-87f21baf29e2.png)

The labels on pages should be a bit more specific. This will also be good for SEO if we use an h2 tag or strong tag. 

![image](https://user-images.githubusercontent.com/845767/60868707-dd355a00-a22d-11e9-94a7-393834b7473f.png)


## Mobile:
Our mobile view doesn't have a visible active state. Instead we need to make sure users can navigate easily within long pages in order to increase discoverability and engagement with our content. This is also beneficial for SEO as anchor links that contain keywords help with ranking. I suppose we can apply this to the expertise and case study pages on mobile.

![image](https://user-images.githubusercontent.com/845767/60868894-40bf8780-a22e-11e9-8eeb-da468028f833.png)

Some sections might require anchors to help organize the content.
![image](https://user-images.githubusercontent.com/845767/60869081-97c55c80-a22e-11e9-9184-3cd0a8d2106f.png)

## Back to top link:
Help users to access top navigation without having to scroll all the way to the top

![image](https://user-images.githubusercontent.com/845767/60869330-115d4a80-a22f-11e9-8c70-e32b531599c6.png)

**Comment by pichfl** [comment]
I'm not sure about the back to top thing. We mirror the navigation in the footer, so we have that covered pretty well and I always find these floating things rather annoying. 

I agree with all the other changes 👍

**Comment by ghislaineguerin** [comment]
@pichfl perfect. I will be updating all the pages on our sketch file to match.
