### ISSUE TITLE
Set up visual regression testing

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#598]
We merged a number of changes in the past that lead to visual regressions that went unnoticed. As that's not great of course and it's quite some manual labor going through all pages with all of the relevant viewport sizes each time we merge anything, we should set up visual regression testing.

That could either be done on a per-component level where it's probably sufficient to test the `Page…` components or with Puppeteer.

percy.io is free for open source projects and well connected with the Ember community so seems to be a good first try. If it doesn't work for some reason, we could use something else as well.

### TODO

- [x] find good service
- [x] find good way of integrating the test cases
- [x] implement
- [x] make this part of our CI pipeline
