### ISSUE TITLE
Verify image descriptions (alt attributes)

### ISSUE THREAD

**Issue by pichfl** [mainmatter/mainmatter.com#645]
#### Todo

- [x] Check if necessary or missing. 
- [x] Many images on our site are purely decoration. Use empty alt attributes for those. 

#### Why

A good image description conveys to a non seeing reader what the image would explain to a seeing reader. If the image is only there to add visual embellishment instead of adding meaning, it should use an empty alt attribute so it can be skipped. The less noise, the better. 

If an image represents a logo, it should have the company name as an alt attribute. If the logo is right next to the very same text, it should be seen as decoration. 

Images with compositions such as a phone showing an app are a bit more difficult. But in general, I would recommend to just describe it as "mobile app x showing step y", as the fact that it's inside a mock phone doesn't hold any meaning to the content.

Overall, keeping it short, concise and close to the main topic is key. 

#### Files with images

- [x] lib/generate-blog/lib/templates/author/template.hbs
- [x] lib/generate-blog/lib/templates/post/template.hbs
- [x] lib/generate-blog/lib/templates/recent-posts/template.hbs
- [x] lib/generate-calendar/lib/templates/page/template.hbs
- [x] lib/generate-talks-archive/lib/templates/page/template.hbs
- [x] src/ui/components/Card/template.hbs
- [x] src/ui/components/ClientsGrid/template.hbs
- [x] src/ui/components/Footer/template.hbs
- [x] src/ui/components/PageCaseStudyTimify/template.hbs
- [x] src/ui/components/PageCaseStudyTrainline/template.hbs
- [x] src/ui/components/PageContact/template.hbs
- [x] src/ui/components/PageEmberExpertise/template.hbs
- [x] src/ui/components/PageHomepage/template.hbs
- [x] src/ui/components/ShapeAcross/template.hbs
- [x] src/ui/components/ShapeBold/template.hbs
- [x] src/ui/components/ShapeDecorative/template.hbs
- [x] src/ui/components/ShapeFeature/template.hbs
- [x] src/ui/components/ShapeWork/template.hbs
