### ISSUE TITLE
Adding dynamic meta tags to head

### ISSUE THREAD

**Issue by pichfl** [mainmatter/mainmatter.com#654]
We need to add several additional HTML meta tags to the `<head>` depending on the page, which means we have to add them to the routing map or find some other way to add these individually.

This issue is only for implementing that mechanism. Necessary tags are determined in #412, #627 and others.

Necessary meta tags:
```html
<meta name="description"  property="og:description" content="...add something with < 165 chars here...">

<meta property="og:site_name" content="simplabs" /> <!-- For all pages, this is the *site*, not the page -->
<meta name="twitter:title" property="og:title" content="Plain page title (ie. just 'Services')" />
<meta property="og:type" content="website" /> <!-- Static for everything but blog pages where it should be `article` -->
<meta property="og:url" content="Canonic URL" />
<meta name="twitter:image:src" property="og:image" content="http://ia.media-imdb.com/images/rock.jpg" /> <!-- image must be at least 280x150px -->
<meta property="fb:admins" content="Facebook numeric ID" /> <!-- Static for everything -->
<meta name="twitter:card" content="summary> <!-- for all pages -->
<meta name="twitter:site" content="@simplabs"> <!-- same for all pages -->
<meta name="twitter:description" content="Duplicates meta name=description"> <!-- optional, twitter may fall back to the other description. Or not. -->

<!-- If we can have those, they would be nice -->
<meta property="article:published_time" content="2013-09-17T05:59:00+01:00" />
<meta property="article:modified_time" content="2013-09-16T19:08:47+01:00" />
```

- [x] figure out where to put these meta tags
- [x] implement the solution
- [ ] Add all necessary meta tags (see list above)

**Comment by marcoow** [comment]
@pichfl I think there's something missing here?

```html
<meta  content="http://www.example.com/image.jpg">
```

**Comment by pichfl** [comment]
@marcoow yes, I just removed it. That one was collapsed into 
```html
<meta name="twitter:image:src" property="og:image" content="path/to/image.jpg" />
```

**Comment by marcoow** [comment]
I'm  closing  this for now as we have as all of  this  is done except for a few tags that are handled via #655, #672.
