### ISSUE TITLE
Meta description and OG tags for blog posts

### ISSUE THREAD

**Issue by pichfl** [mainmatter/mainmatter.com#655]
Needs #654 

Just like regular pages, blog posts need individual meta descriptions and Open Graph tags. 

This includes:
- [meta name=description](https://developer.mozilla.org/de/docs/Web/HTML/Element/meta#attr-name) - `<meta name="description" property="og:description" content="My meta description copy." />` Use that notation to fulfill both description and og:description! 
- <meta name="author" property="article:author" content="...."> - re-use existing field
- og:title - use the title of the blog post 
- og:url - the canonical and full URL for the post
- `<meta property="og:type" content="article">` (applies to all blog posts) 
- `<meta property="article:section" content="$topic">` - Reuse existing topic
- `<meta name="twitter:creator" content="@author_handle">`

To have those, we need to add additional fields to the front matter for future posts.

We should also try to use the excerpt as fallback in case an old post doesn't have these tags. I would try to use just the text from the excerpt without tags and cut at the last word before we reach 160 characters and add an ellipsis.

- [ ] Add new fields to frontmatter
- [ ] Render fields into meta tags (description)
- [ ] Verify fields using [Facebook Debugger](https://developers.facebook.com/tools/debug/) and [Googles Tester](https://search.google.com/structured-data/testing-tool/u/0/)
