### ISSUE TITLE
Replace "Meet us at EmberFest" sidebar teaser

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#726]
We should replace the _"Meet us at EmberFest"_ sidebar teaser as the event is now over.

We are currently showing the teaser on these pages:

* https://simplabs.com
* https://simplabs.com/blog/
* https://simplabs.com/expertise/ember/
* https://simplabs.com/why-simplabs/

### TODOs

- [x] figure out what content we want to show in those places instead (e.g. other particular upcoming event, past events (talks), future events (calendar), teaser to the documentary etc.)
- [x] create new sidebar teaser components for the content chosen above and add that on the pages noted above
- [x] potentially remove the current `CardUpcomingEvents` components and associated assets

**Comment by pichfl** [comment]
Home / Ember Experise
```
Label: Ember.js
Image:  simplabs :heart: ember
Headline: We are official sponsors of Ember.js
Text: simplabs sponsors and support the development of the new Ember.js website
```

Why simplabs
Could also use the Ember.js sponsoring, but I'd actually link to our Talks
```
Label: Sharing knowledge
Image: TBD
Headline: Talks from people at simplabs
Text: We strongly believe in the value of sharing our expertise and experience with others.  
```

**Comment by marcoow** [comment]
@pichfl we have a card for talks already: https://github.com/simplabs/simplabs.github.io/tree/master/src/ui/components/CardTalks

**Comment by marcoow** [comment]
What about

```
Label: Ember.js
Image:  simplabs :heart: ember
Headline: Official Ember.js Sponsor
Text: We have been recognized as official sponsors of the Ember.js project along with international brands like LinkedIn and Yahoo.
```

**Comment by pichfl** [comment]
I know, I was just wondering if it might be good to provide a more contextualized version for that page. Re-using the existing one makes more sense though.

**edit** Too slow for the second comment, but that reads much better.

**Comment by marcoow** [comment]
ah, I see - that makes sense of course 👍

**Comment by pichfl** [comment]
Well it doesn't after all, I overlooked that the page already *has* an instance of that very component.
