### ISSUE TITLE
Add empty state for the calendar page

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#742]
We should have an empty state for when there are no items in the calendar. Right now, we don't have anything coming up (which is fine) but the page looks relatively bad, almost broken:

<img width="1384" alt="Bildschirmfoto 2019-11-08 um 12 01 01" src="https://user-images.githubusercontent.com/1510/68471874-721d8380-021f-11ea-9cf5-f8dbd8977749.png">

I think we should add a message saying something like _"there are currently no events but look at our past talks"_ (linking to `/talks`).

### TODO

- [ ] add a case for when there are no conferences or meetups coming up to the template: https://github.com/simplabs/simplabs.github.io/blob/master/lib/generate-calendar/lib/templates/page/template.hbs
- [ ] come up with a good text
- [ ] add respective HTML, CSS etc.

**Comment by marcoow** [comment]
@marhigh do we have a design for this already?

**Comment by marhigh** [comment]
@marcoow not yet, same answer as the other issue. We can create another column in the kanban board for those issues that aren't yet "ready to develop" - would that be helpful?

**Comment by marhigh** [comment]
Although both still have the "design" label on them so I suppose that is enough 👍

**Comment by marcoow** [comment]
I'd say _"developing"_ anything sometimes means designing, sometimes means coding, often means both so wouldn't separate the two. Was just asking to check whether this was ready for **me** to work on but seems like **you** need to take this on first then 👍

**Comment by marhigh** [comment]
Correct 👍 anything that has the label "design" still needs me to design the visual solution, and would not yet be ready for you to take on. There is a duplicate in notion of each of those tasks for more transparency. 

Calling design "development" is super confusing - happy to exchange further about proper terminology so we don't have a misunderstanding in the future.

**Comment by marcoow** [comment]
I don't have strong opinions about terminology here – main point is the board should reflect **all** work regardless of its kind.
