### ISSUE TITLE
GDPR compliant tracking

### ISSUE THREAD

**Issue by pichfl** [mainmatter/mainmatter.com#745]
The so called "ePVO" (ePrivacy-Verordnung, yes, this is a real thing in Germany) will require us to explicitly ask for consent from users to use and set cookies that are not required for page functionality. As we do not have any page functionality that requires cookies, this means we have to ask visitors of the page if they are fine with being tracked **before** we can set the cookie. 

Sorry for this being in German, but these were the first articles I came across, not sure if this even is a big thing outside of Germany:
- https://www.bvdw.org/themen/recht/kommunikationsrecht-eprivacy/
- https://www.e-recht24.de/artikel/datenschutz/8451-hinweispflicht-fuer-cookies.html
- https://www.e-recht24.de/artikel/datenschutz/11329-e-privacy-verordnung-die-dsgvo-war-erst-der-anfang.html
- https://www.datenschutzbeauftragter-info.de/eprivacy-verordnung-und-cookies-der-aktuelle-stand/

I'm not sure yet how to handle this with Google Analytics. We need to find out if this is a problem and if we have to change something by the time this policy becomes active. It was scheduled for end of 2019, but looking at the graphics on the first link it could until 2021.

It's a mess. 

- [ ] Find out more
- [ ] Find out how Google Analytics is expected to handle this
- [ ] Implement a solution

or 

- [ ] Wait until the situation becomes clearer
