### ISSUE TITLE
Text too small for proper reading on mobile

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#747]
Google Search Console reports text is too small for reading on mobile, see https://search.google.com/search-console/mobile-usability/drilldown?resource_id=sc-domain:simplabs.com&item_key=CAw&utm_source=wnc_10030322&utm_medium=gamma&utm_campaign=wnc_10030322&utm_content=msg_100058679&hl=de. The URLs listed are

* https://simplabs.com/blog/2018/06/27/actix-tcp-client/
* https://simplabs.com/blog/2018/07/24/from-spa-to-pwa/

but I'd be pretty certain that this affects all of our pages potentially as we use the same styles everywhere of course and I'm not aware of any styles on these pages that these pages use that are different from the rest of the pages.

### TODO

- [ ] understand which specific text the report is about and what the minimum text size is
- [ ] come up with a design solution for this (if we increase the size of this particular text, do we have to increase the size of texts that are supposed to be larger as well or will the different text sizes still be different enough after the change?)
- [ ] make the changes in CSS

I guess this makes no change to tackle before finishing #707 which might in fact invalidate this anyway – I'm marking this as blocked by #707 for now.

**Comment by marcoow** [comment]
This is fine now
