### ISSUE TITLE
Add generic fallback og:image

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#857]
We currently have `og:image`s for some of the blog routes (the most popular posts) but we are lacking them for the other routes which means a link to the homepage posted on Twitter will look like this:

<img width="577" alt="Bildschirmfoto 2020-02-03 um 09 05 59" src="https://user-images.githubusercontent.com/1510/73635746-744b7e80-4664-11ea-9227-6a11d3d117ef.png">

while for a blog post with an [`og:image`](https://github.com/simplabs/simplabs.github.io/blob/master/public/assets/images/posts/2020-01-31-how-to-over-engineer-a-static-page/og-image.png) it will like this:

<img width="579" alt="Bildschirmfoto 2020-02-03 um 09 06 15" src="https://user-images.githubusercontent.com/1510/73635760-7ca3b980-4664-11ea-98b0-52a13ef5fb32.png">

We should define a generic `og:image` that we use as a fallback for all pages that do not define a custom one - something as simple as maybe just our logo or so. I think showing **something** will always look better than showing **nothing** or the respective platform's placeholder.

### TODO

- [ ] design generic `og:image` (same size and resolution etc. as the ones we use for blog posts)
- [ ] add a `<HeadTag>` to the `<Simplabs>` component that will render the `og:image` for **every** component (invocations of the `<HeadTag>` component that are rendered **inside** the `<Simplabs>` component will override the previously rendered tag)
- [ ] test (we do not have a good way to test this automatically currently so this will require some manual testing)
