### ISSUE TITLE
Add quote component

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#883]
The new service pages use a differently styles quote component that is in line with new design approach for components we're taking generally. We need to create a component for that that we can use for different quotes from different clients with different photos etc. The organization of this will be similar to the current `ShapeFeature` component that implements the general shape etc. and is used in concrete components like [`ShapeFeatureTimify`](https://github.com/simplabs/simplabs.github.io/tree/master/src/ui/components/ShapeFeatureTimify) etc. then. The general look of the quote component is also the same as the new component we added at the top of the homepage (introduced via #777) so we should be re-using that.

<img width="570" alt="Bildschirmfoto 2020-02-14 um 12 27 50" src="https://user-images.githubusercontent.com/1510/74527242-73003880-4f25-11ea-9e64-9df473342bb5.png">

## TODO

- [x] add a new `ShapeQuoteTimify` component that wraps the `ShapeFeature` component and sets image and content accordingly
- [x] add that component to the digital products page
- [x] create new image for the quote shape

## Resources

* design for digital products page: https://share.goabstract.com/a901d0cd-76b4-4738-b7de-01a24415be15?collectionLayerId=93d765b1-ca1a-41c8-8dbd-66b38317418f
* @ghislaineguerin to decide on (and potentially prepare) which image we use - ideally we can reuse one that we already have
* quote: _"simplabs' experienced engineers delivered a solid and well architected foundation for our web app. They also helped us establish best practices and a lean process internally. Working with them was a pleasure."_ – **ANDREAS KNÜRR, TIMIFY CEO**

**Comment by locks** [comment]
Closed by #899.
