### ISSUE TITLE
Add more variation to work-with-us photos

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#885]
Currently we are only showing Ghislaine, Chris and Marco in the new work-with-us footers (see #828). We should add more variation to make the pages visually more interesting and also represent the team better. This requires making more photos since currently we do not have more than those 3 that would be good enough to be usable.

## TODO

- [x] take more team pictures (will do at on-site in Berlin)
- [x] add the people and photos to https://github.com/simplabs/simplabs.github.io/blob/website-revamp/src/ui/components/WorkWithUs/component.ts#L3
- [x] update the component invocations to use different people on different pages (no particular assignment of people to page necessary)

**Comment by ghislaineguerin** [comment]
![ricardo@604](https://user-images.githubusercontent.com/845767/75457381-b2df0b00-597c-11ea-82f2-726f4f3608c9.png)
![jessica@604](https://user-images.githubusercontent.com/845767/75457396-b70b2880-597c-11ea-8991-d19ed981daf2.png)
![florian@604](https://user-images.githubusercontent.com/845767/75457406-ba061900-597c-11ea-83f0-96016338aeac.png)

@marcoow here are the photos. Toby on dark background didn't work well

**Comment by marcoow** [comment]
Ok, I'll prepare a PR.

**Comment by locks** [comment]
Merged!
