### ISSUE TITLE
Update mobile version of shapes

### ISSUE THREAD

**Issue by locks** [mainmatter/mainmatter.com#905]
Multiple shapes need adjustments for mobile viewports in order to ensure design coherence.

## Tasks
- [x] Make sure image for centered block does not reach the edges on mobile
- [x] Make sure clip shapes align to the left or right accordingly to the same side as the shape
- [x] Remove the header's shape grey background on desktop and mobile

## Resources
- Abstract: https://app.abstract.com/projects/f6401950-547a-11e9-a66d-7f6f3414ea33/branches/38b9d501-75be-4d7d-b595-73b0b6d24f09/commits/f72f0ba696adb025907b00a1b71ce919cc675a22/files/270f3779-b0f4-43d5-b3ac-9665af17512f/layers/9476F84C-1FDF-4C00-BFEE-6EC90DAC5315?mode=design

**Comment by locks** [comment]
Incorporated into https://github.com/simplabs/simplabs.github.io/issues/886.

**Comment by marcoow** [comment]
@locks can we not keep this separate? If there's a strong reason for merging these 2 things, I'm ok with it but if we can we should always keep separate things separate – see the [playbook](https://github.com/simplabs/playbook/tree/master/development-process#feature-branches-and-pull-requests).

**Comment by locks** [comment]
@marcoow

**Comment by marcoow** [comment]
done via #942
