### ISSUE TITLE
Deprecate old shapes and replace with new one

### ISSUE THREAD

**Issue by locks** [mainmatter/mainmatter.com#906]
For the redesign new shapes were introduced for many elements of the website, such as quotes, headers, sidebars.
The task is to go through all the shapes used in the website and make sure they are the new ones.

## Tasks
- [ ] Review website pages for any new shapes that are necessary to design (@ghislaineguerin)
- [ ] Replace old shapes with new shapes

### Shapes
- [ ] Embedd quote on /cases/ddwrt
- [ ] Expedition quote on /cases/expedition
- [ ] Timify quote on /cases/timify
- [ ] Trainline quote on /cases/trainline
- /expertise/ember
  - [x] Documentary shape
  - [ ] team augmentation and tutoring images ?
- /work
  - [x] Trainline mobile web app
  - [x] Timify web app
  - [ ] playbook shape
- /blog
  - [ ] featured post
  - [ ] related blog posts

## Resources
- Abstract for the website: https://share.goabstract.com/f110e8e6-5c22-4df6-a991-d2bbfcc63369?sha=97dcd61cb66a6c122274bf5f8f718cf3767f3db7

**Comment by ghislaineguerin** [comment]
@marcoow Here is the design for the blog main page:
https://share.goabstract.com/7645e3e5-dcec-49e4-a7c9-aa1c16bc5a05?collectionLayerId=4e4b0b44-c724-4f4e-93c4-dd3cea2929dd&mode=design
I will also introduce some slight spacing and typography adjustments to the blog posts in general. And how we can use the featured image for the recommended posts shape.
