### ISSUE TITLE
Remove Full Stack Engineering page

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#917]
With the restructured service pages we are removing the [_"Full Stack Engineering"_ page](https://simplabs.com/services/full-stack-engineering/) (as that gets replaced with the _"Digital Products"_ pages basically). We need to remove that page from the codebase.

### Todo

- [x] remove the `<PageFullStackEngineering>` component
- [x] remove all links to `/services/full-stack-engineering/`
- [x] remove any other components that might be used **only** on `/services/full-stack-engineering/` and are not used on any of the new pages (if any such components exist at all)
- [x] remove /services/full-stack-engineering/ from the route map
- [x] redirect`/services/full-stack-engineering/` to `/services/digital-products/`
- [x] change existing redirect for `/full-stack-engineering/index.html` to go to `/services/digital-products/`

**Comment by marcoow** [comment]
done via #920
