### ISSUE TITLE
Tweak offsets in digital products page

### ISSUE THREAD

**Issue by locks** [mainmatter/mainmatter.com#958]
The clipped images work was not fully completed as some of the offsets are not correct and need updating.
Blocks that separate two sections should use the offset `after-21`, these include `bleed-right` blocks since on mobile viewport they will be at the end of a section.

## Tasks
- [ ] Fix offsets in digital products page
  - [ ] https://github.com/simplabs/simplabs.github.io/pull/898/files#r390551275
  - [ ] https://github.com/simplabs/simplabs.github.io/pull/898/files#r390551466
  - [ ] https://github.com/simplabs/simplabs.github.io/pull/898/files#diff-e361308ad4d1619c58e247efca1bfaeeR137
- [ ] Use `after-16` for `bleed-left` and `split-leading` blocks
- [ ] Use `after-21` for `bleed-right` and `split-trailing` blocks

## Resources
- Abstract: https://app.abstract.com/projects/f6401950-547a-11e9-a66d-7f6f3414ea33/branches/38b9d501-75be-4d7d-b595-73b0b6d24f09/collections/e312bf18-d9c5-4f10-853b-2f2acbe2e4a1

**Comment by locks** [comment]
Closed via #957.
