### ISSUE TITLE
Replace Trainline quote with Qonto quote

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#963]
We just added the Trainline quote but I realized we have a pretty good one from Qonto that we could use instead since we're referring to Trainline in quite a few other places already. We can simply replace the `<ShapeQuoteTrainline>` component with a `<ShapeQuoteQonto>` component and update all usages of the component respectively.

### TODO

- [ ] create image for the quote component
- [ ] rename `<ShapeQuoteTrainline>` to `<ShapeQuoteQonto>` and update usages
- [ ] replace quote from Carl with the quote from Marc-Antoine below

### Resources

* Quote: _"simplabs are well known as the Ember.js experts and they absolutely live up to the expectations. They had an immediate as well as significant positive impact on both our velocity and quality of output. - Marc-Antoine Lacroix, Qonto CTO"_
* Image: we could use something from their [media kit](https://projects.invisionapp.com/boards/9T3UDRXEHSN) maybe?

**Comment by ghislaineguerin** [comment]
![image](https://user-images.githubusercontent.com/845767/76408520-5c66c900-638d-11ea-9502-595e0fea7b8d.png)

This image from the media kit could work. Are we allowed to use it?

**Comment by marcoow** [comment]
I'm checking with Qonto but I think we can assume we can use it for now.

**Comment by marcoow** [comment]
done via #968
