### ISSUE TITLE
Rename "Tutoring" to "Training and Support"

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#976]
We have renamed the _"Tutoring"_ service to _"Training and Support"_. However, we are still referring to it as _"Tutoring"_ in some places and the URL is `/services/tutoring/` as well.

### TODO

- [x] change URL from `/services/tutoring/` to `/services/training/`
- [x] redirect `/services/tutoring/` to `/services/training/` via `netlify.toml`
- [x] change link in footer from _"Tutoring"_ to _"Training and Support"_
- [x] change titles and label in header on `<PageTutoring>`
- [x] rename `<PageTutoring>` component to `<PageTrainingAndSupport>`

**Comment by marcoow** [comment]
done via #978
