### ISSUE TITLE
Finalize header content of services pages

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#977]
Some of the services pages still have old header content or document titles which need to be updated to reflect the new service structure and naming.

### TODO

- [x] change `@documentTitle` of `<PageServices>` header to _"@documentTitle="Digital Products & Team Augmentation & Training and Support | Our Services""_
- [x] fix typo in `@description` (_"…and help**s** tech teams move…"_)
- [x] change `@description` of `<PageProductDesign>` to _"We provide product design expertise throughout the entire product creation process—from rough concept sketches to tested, final implementation."_
- [x] change `@description` of `<PageProductDevelopment>` to _"Engineering is our true passion, and unmistakable in every product we deliver."_

**Comment by marcoow** [comment]
done via #979
